name: React App workflow

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!


  build:

    needs: hello-world

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup node.js version 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build
